from enum import StrEnum


class Role(StrEnum):
    REVIEWER = "REVIEWER"
    ADMIN = "ADMIN"


class Route(StrEnum):
    DOUBLE_BLIND = "DOUBLE_BLIND"
    DOUBLE_BLIND_AUDIT = "DOUBLE_BLIND_AUDIT"
    SINGLE_VISIBLE_REVIEW = "SINGLE_VISIBLE_REVIEW"
    DOUBLE_BLIND_TEST = "DOUBLE_BLIND_TEST"


class CaseStatus(StrEnum):
    ASSIGNED = "ASSIGNED"
    IN_REVIEW = "IN_REVIEW"
    WAITING_SECOND_REVIEW = "WAITING_SECOND_REVIEW"
    RESOLVED_HUMAN_AGREEMENT = "RESOLVED_HUMAN_AGREEMENT"
    DISCUSSION_REQUIRED = "DISCUSSION_REQUIRED"
    DISCUSSION_IN_PROGRESS = "DISCUSSION_IN_PROGRESS"
    RESOLVED_DISCUSSION = "RESOLVED_DISCUSSION"
    ADJUDICATION_REQUIRED = "ADJUDICATION_REQUIRED"
    RESOLVED_ADJUDICATION = "RESOLVED_ADJUDICATION"
    RESOLVED_VISIBLE_ACCEPT = "RESOLVED_VISIBLE_ACCEPT"
    RESOLVED_VISIBLE_EDIT = "RESOLVED_VISIBLE_EDIT"


DOUBLE_ROUTES = {Route.DOUBLE_BLIND, Route.DOUBLE_BLIND_AUDIT, Route.DOUBLE_BLIND_TEST}
FINAL_STATUSES = {
    CaseStatus.RESOLVED_HUMAN_AGREEMENT,
    CaseStatus.RESOLVED_DISCUSSION,
    CaseStatus.RESOLVED_ADJUDICATION,
    CaseStatus.RESOLVED_VISIBLE_ACCEPT,
    CaseStatus.RESOLVED_VISIBLE_EDIT,
}
